added map auto scroll
ya-pomogau/frontend-fork pull request #121
Opened 2023-08-24 21:23 UTC by BreadLinx

2023-08-24 21:24 UTC, BreadLinx commented
Функциональность такая нормальная? Просто я понятия не имею по каким формулам пересчитывать зум в пиксели

2023-08-25 04:58 UTC, vierim requested changes
Данное решение не очень удачное, так как:
1) карта центрирует Mark, даже если весь тултип виден, а нам нужно скролить карту только в том случае, если тултип не виден;
2) карта скачет, а и не аккуратно скролится.

Посмотри документацию и git используемой библиотеки (или той, откуда она форкнута), может там в issues что-то есть на данную тему.

2023-10-28 12:45 UTC, AleksandrDronov commented
Я изначально делал какрту. И у меня не получилось разобраться с api карт на предмет центирования карты по балуну. В данном коммите решение некорреткное. Предлагаю выделить в отдельную таску. Данная задача очень нетривиальная.

2023-10-29 17:30 UTC, kspshnik commented
Перенесено в issues основного репозитория

2023-10-29 17:30 UTC, closed without merging