Feature/register page
ya-pomogau/frontend-fork pull request #131
Opened 2023-10-12 10:49 UTC by marussia1996

Сверстала страничку Регистрации. При выборе "Нужна помощь" или "Хочу помочь" изменяется контент на страничке. Также сделала так чтобы окно с информацией о пользователе было пустое, если пользователь находится на странице регистрации (как в макете).

2023-10-14 13:04 UTC, kspshnik requested changes
Критическое - это разделение на страницы, остальное уже пожелательное.

2023-10-14 13:04 UTC, kspshnik commented on src/pages/register/index.tsx
>        coords: coords || [],
Как определяются и откуда импортируются `coords` ?

2023-10-14 13:04 UTC, kspshnik commented on src/pages/register/index.tsx
> +    setShowLoginButton(true);
А почему это  "toggle" ? %)

2023-10-14 13:04 UTC, kspshnik commented on src/pages/register/index.tsx
> +      {!changeContent && (
Мне кажется, это надо растащить по двум разным страницам: регистрации и подтверждения ПД. Иначе мы в будущем не сможем поменять действия местами без масштабного рефакторинга.

2023-10-15 11:12 UTC, marussia1996 commented on src/pages/register/index.tsx
> +    setShowLoginButton(true);
на visibleLoginButton норм переименование?

2023-10-15 11:15 UTC, marussia1996 commented on src/app/routing/router.tsx
Если решим все таки сделать еще одну страницу для отдельной работы с бэком при авторизации через ВК, то заведем задачу.

2023-10-15 11:48 UTC, kspshnik approved these changes

2023-10-18 20:13 UTC, AlexeyNewDeveloper approved these changes

2023-10-20 13:45 UTC, merged