politico + errors in the text
ya-pomogau/frontend-fork pull request #132
Opened 2023-10-12 17:11 UTC by Zdthns

Исправлены ошибки в слове конфидециальность,  доделана политика конфиденциальности, внесена в storybook

2023-10-14 10:49 UTC, marussia1996 commented on src/pages/policy/politico.stories.tsx
переименуй название файла в policy.stories

2023-10-14 13:07 UTC, kspshnik reviewed
Содержимое положения о конфиденциальности надо получать с сервера и класть в системный слайс Redux, по хорошему.

2023-10-15 08:42 UTC, AleksandrDronov requested changes
1. Чем вызвано использование markdown разметки, а не HTML? В результате в проекте два доп пакета. 
2. Верстка не совпадает с макетом. (шрифты, отступы). 
<img width="690" alt="image" src="https://github.com/ya-pomogau/frontend-fork/assets/93670312/0427ff47-296a-4982-91a1-23a39925fb5c">

2023-10-15 08:42 UTC, AleksandrDronov commented on src/pages/policy/politico.stories.tsx
> +/* eslint-disable */
Не допускается так дизайблить. Если есть ошибки линтера или притера их необходимо устранить.

2023-10-15 08:42 UTC, AleksandrDronov commented on src/pages/policy/politico.stories.tsx
История написана без типизации. Необходимо затипизировать. Можно посмотреть как написаны другие истории. А вообще истории для страниц мы не пишем. Так что история не нужна.

2023-10-15 09:03 UTC, kspshnik commented
> 1. Чем вызвано использование markdown разметки, а не HTML? В результате в проекте два доп пакета.
А вводить администратор и бэкенд хранить будет тоже HTML? :)
Это **не** статический контент по ТЗ. 
Хранить и особенно вводить HTML - это *очень* плохая идея и открытые ворота на тему "поломайте мой сайт".

2023-10-15 09:06 UTC, kspshnik commented on src/pages/policy/politico.stories.tsx
> А вообще истории для страниц мы не пишем. Так что история не нужна.

Вопрос: а почему мы не пишем истории для страниц? Это была выработана такая позиция изначально? Или просто раньше не писали?

2023-10-15 10:25 UTC, AleksandrDronov commented on src/pages/policy/politico.stories.tsx
Такая изначально. Ну и плюс сторибук это библиотека компонентов. Обычно в практике не видел, чтобы прям целые страницы заносили.

2023-10-15 10:26 UTC, AleksandrDronov commented on src/pages/policy/politico.stories.tsx
Смысл сторибука в том, что пришел туда взял уже кем-то разработанный компонент и используешь у себя.

2023-10-15 10:31 UTC, AleksandrDronov commented
> > 1. Чем вызвано использование markdown разметки, а не HTML? В результате в проекте два доп пакета.
> 
> А вводить администратор и бэкенд хранить будет тоже HTML? :) Это **не** статический контент по ТЗ. Хранить и особенно вводить HTML - это _очень_ плохая идея и открытые ворота на тему "поломайте мой сайт". Можно хранить текст или другую, не-HTML разметку. MarkDown позволяет и определённую стилизацию применить, и риски XSS не затягивает в проект, и санитизация минимальная требуется.
> 
> И пакеты не лишние - нам ещё блоги как-то хранить, лучше это тоже в MD делать :)

Если политика редактируется в админке, то согласен.

2023-10-15 11:07 UTC, kspshnik commented on src/pages/policy/politico.stories.tsx
> Смысл сторибука в том, что пришел туда взял уже кем-то разработанный компонент и используешь у себя.

Согласен. Но тогда по уму страницы надо покрывать тестами.

2023-10-18 11:03 UTC, Zdthns commented on src/pages/policy/politico.stories.tsx
Чтобы типизировать историю, нужна динамика. А в данном компоненте(странице) ее нет.

2023-10-18 11:06 UTC, Zdthns commented on src/pages/policy/politico.stories.tsx
> +/* eslint-disable */
это обсуждалось. На данном этапе почти в каждом компоненте так. Нужна перенастройка линтера для всех

2023-10-19 05:53 UTC, AleksandrDronov requested changes
Все еще требуется доработка в части стилей. 

<img width="1012" alt="image" src="https://github.com/ya-pomogau/frontend-fork/assets/93670312/852c23fc-bd20-4c33-8ae6-e14f319fa751">

2023-10-19 05:53 UTC, AleksandrDronov commented on src/pages/policy/content.tsx
>  /* eslint-disable */
Тут также необходимо поправить ошибки линтера.

2023-10-19 05:53 UTC, AleksandrDronov commented on src/pages/policy/markdown-style.module.css
> +    font-family: Golds;
Опечатка в слове Golos

2023-10-19 05:53 UTC, AleksandrDronov commented on src/pages/policy/politico.stories.tsx
Для страниц историю не делаем

2023-10-19 09:36 UTC, Zdthns commented on src/pages/policy/content.tsx
>  /* eslint-disable */
к сожалению, в данном месте победить линтер не получится, так как отступы в markdown задаются пробелами, а линтер будет выдавать ошибку на лишние пробелы. Конечно можно заморочится и сделать блочную HTML разметку и нарезать  markdown  на мелкие части, чтобы повставлять в каждый блок и хранить эти части на сервере кусочками.... Но оно того стоит?

2023-10-19 10:10 UTC, Zdthns commented on src/pages/policy/content.tsx
>  /* eslint-disable */
по поводу PixelPerfect...   Вес, размер и высота шрифта соответствуют макету.  Отступы заданы согласно синтаксису  markdown. Рендеринг шрифтов напрямую зависит от браузера и операционной системы, по этому не стоит ждать 100% совпадения.

2023-10-19 11:28 UTC, kspshnik commented on src/pages/policy/content.tsx
>  /* eslint-disable */
Это же "затычка" на время неготовности бэкенда и будет заменена на данные с бэка?

Если так, то @AleksandrDronov - а не пофигу ли на эту типа ошибку? Через неделю-две этот файл в /dev/null пойдёт стройными рядами :)

2023-10-19 11:48 UTC, Zdthns commented on src/pages/policy/content.tsx
>  /* eslint-disable */
и все же я еще подправила стили. В моем браузере выглядит почти 100% :)
![image](https://github.com/ya-pomogau/frontend-fork/assets/89003491/3eb87b34-c44d-4897-b9c1-45bd122434f4)

2023-10-19 13:13 UTC, AleksandrDronov commented on src/pages/policy/content.tsx
>  /* eslint-disable */
> к сожалению, в данном месте победить линтер не получится, так как отступы в markdown задаются пробелами, а линтер будет выдавать ошибку на лишние пробелы. Конечно можно заморочится и сделать блочную HTML разметку и нарезать markdown на мелкие части, чтобы повставлять в каждый блок и хранить эти части на сервере кусочками.... Но оно того стоит? Хотя, возможно у тебя есть какие то предложения? Возможно, ты знаешь какой то путь для решения данной проблемы?

Я победил линтер в данном месте. 
<img width="583" alt="image" src="https://github.com/ya-pomogau/frontend-fork/assets/93670312/b11686c0-d960-4202-b3d8-5c7859990894">

2023-10-19 13:15 UTC, AleksandrDronov commented on src/pages/policy/content.tsx
>  /* eslint-disable */
> Это же "затычка" на время неготовности бэкенда и будет заменена на данные с бэка?
> 
> Если так, то @AleksandrDronov - а не пофигу ли на эту типа ошибку? Через неделю-две этот файл в /dev/null пойдёт стройными рядами :)

Это да. Но на данном этапе пишу, что вижу :).

2023-10-19 13:18 UTC, AleksandrDronov commented on src/pages/policy/content.tsx
>  /* eslint-disable */
> по поводу PixelPerfect... Вес, размер и высота шрифта соответствуют макету. Отступы заданы согласно синтаксису markdown. Рендеринг шрифтов напрямую зависит от браузера и операционной системы, по этому не стоит ждать 100% совпадения.

Обычно в тз пишется сколько возможно несовпадение. У нас на другом проекте было  макс 10px. У тебя я явно намного привышает размные пределы.

2023-10-19 14:16 UTC, kspshnik commented on src/pages/policy/content.tsx
>  /* eslint-disable */
> > Это же "затычка" на время неготовности бэкенда и будет заменена на данные с бэка?
> > Если так, то @AleksandrDronov - а не пофигу ли на эту типа ошибку? Через неделю-две этот файл в /dev/null пойдёт стройными рядами :)
> 
> Это да. Но на данном этапе пишу, что вижу :).

Предлагаю на эту "ошибку типизации" - забить :)

2023-10-19 18:54 UTC, Zdthns commented
Александра Дронов
1. исправлено
2. исправила, но в ущерб PixelPerfect, так как в markdown есть 2 способа исполнения таких видов отступов(когда они большие) - это code  или цитата. Сделала сейчас цитатой, но у нее заданный програмно интервал, 
3. Тут абсолютно согласна, но  это нужно править другой компонент - основную разметку, Кстати, оверлей тут есть, только он смещен под карту, как на главной странице. В любом случае нужно написать эту правку в задачи по фронту для основной разметки

2023-11-03 16:27 UTC, kspshnik commented
Надо посмотреть и забрать, если не тк

2023-11-04 15:58 UTC, marussia1996 commented
Постаралась сделать  разметку такую же как в макете, добавила прокрутку, если политика будет выходить за рамки страницы, так же добавила логику к overlay который находится внизу страницы, для страниц blog и politicy оверлей на всю страницу располагается, для остальных на определенную часть)

2023-11-17 17:13 UTC, kspshnik approved these changes

2023-11-20 12:58 UTC, INextYP approved these changes

2023-11-20 13:37 UTC, merged