Feat/Vklogin
ya-pomogau/frontend-fork pull request #133
Opened 2023-10-14 16:40 UTC by VladislavSerKir

Добавлена возможность входа через ВК 
Так же создал приложение: https://vk.com/editapp?id=51769265&section=options
env конфигурации
![2023-10-14_19-39-38](https://github.com/ya-pomogau/frontend-fork/assets/83783362/0dde4198-8117-4ad4-87a8-55f4c47a09cc)

2023-10-14 18:16 UTC, kspshnik requested changes

2023-10-14 18:16 UTC, kspshnik commented on src/pages/login/index.tsx
> +    window.location.href = `https://oauth.vk.com/authorize?client_id=${process.env.REACT_APP_CLIENT_ID}&display=popup&redirect_uri=${cbLink}&scope=email&response_type=code&v=5.120&state=4194308`;
В React-приложении мы **не обращаемся** к `window.location`, да и к `window` или `document` в целом за *редчайшими* исключениями.

2023-10-14 18:16 UTC, kspshnik commented on src/pages/login/index.tsx
> +    if (isError) window.location.href = cbLink;
Не мутируем напрямую, используем предоставляемые RR6 хуки

2023-10-14 18:16 UTC, kspshnik commented on src/pages/login/index.tsx
> +  const cbLink = `${host}/login`;
Нет. Нам нужна другая "техническая" страница (возможно, общая с регистрацией), которая будет принимать код от ВК и дёргать бэкенд, перенаправляя на главную или на продолжение регистрации в зависимости от.

2023-10-14 18:16 UTC, kspshnik commented on src/pages/login/index.tsx
> +import { useSigninVkMutation } from 'services/user-api';
Возможно, RTK Query **именно** для этой страницы не является оптимальным выбором - мы всё-равно вытаскиваем данные и диспатчим в более другое место, не используем самосоздаваемый слайс.

2023-10-16 19:32 UTC, VladislavSerKir commented on src/pages/login/index.tsx
> +  const cbLink = `${host}/login`;
Я не совсем понял зачем нужно отправлять на страницу регистрации если это подразумевается кнопка входа через ВК. Сам процесс входа мне представляется так: по кнопке открывается приложение вк с возможностью входа через VK ID пользователя и возвращает уникальный код (уникален для каждого пользователя). Далее фронт отправляет этот код на бэк, на нем уже в свою очередь идет поиск пользователя по базе с этим кодом. Далее идет возврат объекта пользователя. Не понял вопроса, уточни пожалуйста 
![Авторизация через ВК NestJS + React  Andrew Boev  Medium](https://github.com/ya-pomogau/frontend-fork/assets/83783362/6765dee8-4aab-43a6-a91c-2440cc48d3d2)

2023-10-16 19:42 UTC, VladislavSerKir commented on src/pages/login/index.tsx
> +    window.location.href = `https://oauth.vk.com/authorize?client_id=${process.env.REACT_APP_CLIENT_ID}&display=popup&redirect_uri=${cbLink}&scope=email&response_type=code&v=5.120&state=4194308`;
Совершенно согласен что использование и мутирование встроенного в среду браузера объекта window не является хорошей практикой. Но прочитав какие есть аналоги по переходу на другой домен этот метод тоже рассматривается и я так полагаю является превуалирующим, можно использовать например метод replace вместо напрямую мутирования ссылки href. Методы хука useNavigate react-router-dom позволяют делать навигацию толко по роутам домена. Опять таки может я что то не понимаю, если есть какой то другой способ решить кейс с радостью готов узнать
https://codefrontend.com/reactjs-redirect-to-url/
https://atomizedobjects.com/blog/react/how-to-redirect-in-reactjs/

2023-10-16 19:58 UTC, kspshnik commented on src/pages/login/index.tsx
> +  const cbLink = `${host}/login`;
> Я не совсем понял зачем нужно отправлять на страницу регистрации если это подразумевается кнопка входа через ВК. Сам процесс входа мне представляется так: по кнопке открывается приложение вк с возможностью входа через VK ID пользователя и 

Не приложение открывается, а происходит **редирект** на ВК. А потом ВК возвращает управление нам, переходя по заданному заранее URL, в query params которого передаёт нам silent token  (и vk id до кучи). 
Вот для этого и нужна "техническая" страница - вытащить параметры из url и отправить запрос на бэк, крутя прелоадер. И раскидать по факту ответа.

2023-10-16 20:00 UTC, kspshnik commented on src/pages/login/index.tsx
> +  const cbLink = `${host}/login`;
Посмотри PR #131 от @marussia1996 , resolved issues. Там про это вовсю есть :)

2023-10-16 20:30 UTC, kspshnik commented on src/pages/login/index.tsx
> +    window.location.href = `https://oauth.vk.com/authorize?client_id=${process.env.REACT_APP_CLIENT_ID}&display=popup&redirect_uri=${cbLink}&scope=email&response_type=code&v=5.120&state=4194308`;
Да, RR6 не умеет. Вопрос снят :)

2023-10-30 11:46 UTC, marussia1996 reviewed
Внесла изменения по страничкам регистрации, убрала выбор роли на первой странице и добавила на второй. Накидала примерную логику действий после получения данных от сервера в TODO

2023-11-20 13:25 UTC, kspshnik requested changes

2023-11-20 13:25 UTC, kspshnik commented on src/config/api-config.ts
> +  process.env.REACT_APP_MODE === 'production'
Непонятно назначение этого. В приложении доступна нормальная `process.env.NODE_ENV`

2023-11-22 15:10 UTC, marussia1996 reviewed
env файл выглядит так, заменился id приложения
REACT_APP_API_HOST='https://api.kraev.nomoredomains.xyz/api'
REACT_APP_HOST_PROD='https://api.kraev.nomoredomains.xyz'
REACT_APP_CLIENT_ID='51798618'
REACT_APP_HOST_DEV='http://localhost:3001'
REACT_APP_HOST_LOCAL='http://localhost:3001'
REACT_APP_MODE=development

2023-11-22 15:14 UTC, marussia1996 commented on src/entities/user/ui/user-info/index.tsx
> +  const location = useLocation();
это для того чтобы когда user null но при этом мы уже находимся на логине или регистрации у нас не показывалось ничего в блоке профиля. так по макету нужно.

2023-11-22 15:14 UTC, marussia1996 commented on src/config/api-config.ts
> +  process.env.REACT_APP_MODE === 'production'
ты уже подправил это

2023-11-22 15:17 UTC, marussia1996 commented on src/entities/user/ui/user-info/index.tsx
>    const userId = () => {
убрала

2023-11-24 19:38 UTC, kspshnik approved these changes

2023-11-27 17:11 UTC, INextYP approved these changes
Умничка :)

2023-11-27 17:11 UTC, INextYP commented on src/entities/user/ui/user-info/index.tsx
Опять же, не критическая ошибка, но для улучшения общей читабельности кода рекомендую формировать сгруппированный порядок импортов:
- импорты библиотек
<пробел>
- shared слой
<пробел>
- ещё какая-то группа
<пробел>
- стили

2023-11-27 17:11 UTC, INextYP commented on src/pages/login/index.tsx
>    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
`React.ChangeEvent<HTMLInputElement>` - не нужно тянуть реакт из глобальной области видимости. Конкретный тип эвента лучше доставать, используя деструктуризацию
`import { ChangeEvent } from 'React'`

2023-11-28 13:01 UTC, merged