Прокинул кнопку настройки в Стори
ya-pomogau/frontend-fork pull request #136
Opened 2023-10-20 17:10 UTC by AlexeyNewDeveloper

Теперь карточка пользователя и кнопка настроек пользователя отображается корректно в сторибук

2023-10-23 17:02 UTC, marussia1996 approved these changes

2023-10-28 08:47 UTC, AleksandrDronov requested changes

2023-10-28 08:47 UTC, AleksandrDronov commented on src/entities/user/ui/user-info/index.tsx
> +  // const { data: user } = useGetUserByIdQuery(userId() ?? skipToken);
В результате данного рефакторинга остался ненужный код. Его следует удалить. Также можно и удалить это комментарий.  И судя по всему в проекте хук `useGetUserByIdQuery`  не нужен, так как мы берем пользователя из стора. Тогда думаю в рамках это ПРа стоит удалить этот хук из проекта.

<img width="749" alt="image" src="https://github.com/ya-pomogau/frontend-fork/assets/93670312/306c6203-25e2-49a9-a2e3-79062120b8c6">

2023-10-28 11:17 UTC, AleksandrDronov approved these changes

2023-10-28 11:18 UTC, AleksandrDronov commented
Конфликт нудно пофиксить

2023-10-29 07:50 UTC, AleksandrDronov approved these changes

2023-10-29 08:00 UTC, merged