[Feature] System slice
ya-pomogau/frontend-fork pull request #138
Opened 2023-11-19 14:45 UTC by kspshnik

Slice for system information & User. Supports login processes and supplies selectors for user data.

2023-11-19 16:36 UTC, marussia1996 commented on src/services/auth.types.ts
> +// TODO: Удалить лишнее по типу авторизации
что значит удалить лишнее по типу авторизации?

2023-11-19 17:03 UTC, kspshnik commented on src/services/auth.types.ts
> +// TODO: Удалить лишнее по типу авторизации
Это значит, что есть несколько вариантов авторизации через ВК, исходя из документации. Сейчас в dto заложены оба два, как сделаем реально - либо `code` либо `silentToken` свистнут дырочкой в боку и улетят в форточку :)

2023-11-19 17:06 UTC, marussia1996 commented on src/services/auth.types.ts
> +// TODO: Удалить лишнее по типу авторизации
понял

2023-11-19 17:06 UTC, marussia1996 approved these changes
Выглядит круто!) Ты молодец)

2023-11-20 11:51 UTC, INextYP requested changes

2023-11-20 11:51 UTC, INextYP commented on src/config/api-config.ts
>  export const API_URL = 'http://localhost:3001/';
я бы стразу посоветовал вынести вынести эту переменную в .env

2023-11-20 11:51 UTC, INextYP commented on src/services/system-slice.ts
> +    logout: () => systemSliceInitialState,
Тут же ещё и токен нужно очистить, если там таковой присутствует

2023-11-20 12:14 UTC, kspshnik commented on src/config/api-config.ts
>  export const API_URL = 'http://localhost:3001/';
Мария в своей ветке вынесла :) Вмёржим - поправим?

2023-11-20 13:32 UTC, kspshnik commented on src/services/system-slice.ts
> +    logout: () => systemSliceInitialState,
Безусловно. В **обработчике выхода в приложении**, откуда этот action и диспатчится :) 
А тут только чистим стейт.

2023-11-20 13:32 UTC, kspshnik commented on src/config/api-config.ts
>  export const API_URL = 'http://localhost:3001/';
Уже сделал.

2023-11-20 13:42 UTC, INextYP approved these changes

2023-11-20 13:49 UTC, merged