Chats
ya-pomogau/frontend-fork pull request #94
Opened 2023-08-15 13:43 UTC by KirillKamratov

Сделал верстку компонента "чат" и минимальную логику.
Чтобы не возвращаться в дальнейшем - прошу посмотреть, что получилось и дать комментарии

+Если возможно - попросил бы подсказать по пунктам, что из логики необходимо добавить (из макета не все очевидно) - понятно, что нужно добавить закрытие чата на кнопку и смену конфликта (когда начинаешь работать с ним) на 2 чата.

2023-08-16 11:11 UTC, anastasia-bazaeva requested changes
Молодец! Проделана отличная и очень большая работа. Есть несколько замечаний по коду, и отдельно хочется сказать, что нам наверняка понадобится помощь Оли, потому что нам явно не хватает в макете описания чатов. 
- Надо будет уточнить описание того, что происходит при открытии конфликта - кто и по какому событию инициирует, как выглядит окно открытия конфликта, как выглядит уже закрытый конфликт у админа, и по какому событию админ от экрана описания конфликта переходит к двум чатам с каждой из сторон, и как потом вернуться к экрану с описанием конфликта. Давай с ней свяжемся, чтобы эти моменты нам уточнили.
- Отмечу про отображение - на макете чат на верхней панели закреплен только у админов, у всех остальных чаты доступны в окне попапа при нажатии на значок диалога, там где задачи. Новые уведомления в чате видны там же на иконке диалога в задачах. 
![чат01](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/2b40e448-d367-43c8-b3b4-eee6d6a1ee91)
![чат02](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/3734e9ce-a247-4062-b45d-5b919d21d61f)
- Разграничение по ролям ты не делал в рамках задачи? У всех сейчас доступен вид, как у админа, включая неавторизованного пользователя.

2023-08-16 12:43 UTC, KirillKamratov commented on src/widgets/chats/components/Chat/index.tsx
> +                Волонтер достиг 3-го уровня доверия. Выдайте ему ключ
@anastasia-bazaeva да, я понимаю, я как раз поэтому на первый PR и отправил. 
Видимо, тут логика такая, что при закрытии задач волонтер получает баллы, и в случае, если кол-во баллов превысило какой-то порог - это высвечивается (и то, только у админа)

2023-08-16 12:45 UTC, KirillKamratov commented on src/widgets/chats/components/Chat/index.tsx
> +                Здравствуйте, спасибо, что обратились.
@anastasia-bazaeva тут нужно уточнять у Оли и @vierim. Я согласен, что лучше рендерить фразы из какого-то компонента стороннего (типа autoanswers в ui), но я не уверен, по поводу того, что это только у админов высвечивается

2023-08-16 12:46 UTC, KirillKamratov commented on src/widgets/chats/components/chats-list/chats-list.tsx
> +                {chat.notifications}
@anastasia-bazaeva Вообще, форма как раз на макете искажена и там овальчик, а не кружок, я поэтому так и сделал

![image](https://github.com/vierim/YaPomogayu-frontend/assets/102192184/a2f70a6a-97f5-4e1a-81f6-10a2fb266fba)

там и в уведомлениях сверху та же история. Опять же - уточню у Оли, как лучше сделать)

Касательно самого кружка - его наверное в common лучше вывести

2023-08-16 12:47 UTC, KirillKamratov commented
@vierim нам, похоже требуется немного твоего вмешательства (тут не спор, скорее обсуждение)

2023-08-16 12:54 UTC, vierim commented on src/widgets/chats/components/Chat/index.tsx
> +                Здравствуйте, спасибо, что обратились.
Автоответы только у админов.

2023-08-16 12:55 UTC, anastasia-bazaeva commented on src/widgets/chats/components/Chat/index.tsx
> +                Волонтер достиг 3-го уровня доверия. Выдайте ему ключ
> @anastasia-bazaeva да, я понимаю, я как раз поэтому на первый PR и отправил. Видимо, тут логика такая, что при закрытии задач волонтер получает баллы, и в случае, если кол-во баллов превысило какой-то порог - это высвечивается (и то, только у админа)

Спасибо что уточнил, и извини, что я как-то не сообразила более емко подсказать 😅 - да, там есть своя мудреная логика. Баллы даются, но мы их для нового уровня статуса не считаем, а смотрим на количество завершенных заявок, их должно быть более 60. Именно успешно завершенных, а не просто закрытых. 

@vierim мы когда делали модель данных пользователя, решили убрать количество завершенных заявок, а вот тут кажется, что оно было бы полезным. Как лучше - хранить его в модели юзера, или дергать в момент завершения заявки (или в еще какой-то момент) какую-то ручку и проверять ответ от бека, и при количестве более 60 отправлять админу уведомление в чат?

2023-08-16 12:59 UTC, anastasia-bazaeva commented on src/widgets/chats/components/chats-list/chats-list.tsx
> +                {chat.notifications}
А ведь и правда, в макете кружки тоже не кружки. Тогда получается все четко) Но я думаю, что это дизайнер не совсем опытный и не везде правильно сделал иконки, нас как раз предупреждали на одной из установочных встреч послеживать за макетом, потому что дизайнер где-то мог не тот шрифт, форму или текст выбрать

2023-08-16 13:05 UTC, vierim commented on src/widgets/chats/components/Chat/index.tsx
> +                Здравствуйте, спасибо, что обратились.
@KirillKamratov на скрине ведь админская панель.

2023-08-16 13:09 UTC, anastasia-bazaeva commented on src/widgets/chats/components/Chat/index.tsx
> +                Волонтер достиг 3-го уровня доверия. Выдайте ему ключ
Саму проверку скорее всего будем делать не мы, раз мы уже не храним данные про завершенные заявки (хотя вдруг захотим), но нам надо будет все равно договориться как и в какой момент ловить уведомление от бека, чтобы отобразить эту нотификацию и передать ребятам наши идеи, как бы мы хотели это уведомление получать

2023-08-16 13:18 UTC, vierim commented on src/widgets/chats/components/Chat/index.tsx
> +        {window.location.pathname.includes('/in-work') ? (
Расскажи, пожалуйста, чем это хорошо? 
Мне кажется, что это скорее неудачное решение, но я могу чего-то не учитывать.

2023-08-16 13:27 UTC, vierim commented on src/widgets/chats/components/Chat/index.tsx
> +                Волонтер достиг 3-го уровня доверия. Выдайте ему ключ
Проверку бизнес-логики на фронте я бы делать не стал - все таки желательно иметь один источник истины (в данном случае в виде сервера). А вот необходимость получать в чат сообщения разного типа - это действительно момент, который нужно будет решать с беком.

2023-08-16 13:29 UTC, vierim commented on src/widgets/chats/components/Chat/index.tsx
> +        {window.location.pathname.includes('/in-work') ? (
В моем понимании, мы делегировали всю логику для работы с роутингом приложения в react-router и теперь не совсем корректно самостоятельно обращаться к нативным методам браузера. Правильней будет использовать методы, которые предоставляет библиотека.

2023-08-16 13:38 UTC, anastasia-bazaeva commented on src/widgets/chats/components/Chat/index.tsx
> +        {window.location.pathname.includes('/in-work') ? (
Спасибо большое за комментарий, я поняла, в чем не права - правильнее работать с useHistory и useLocation из react-router-dom

2023-08-16 13:41 UTC, KirillKamratov commented on src/pages/chats-conflicts/index.tsx
> +              isMobile={isMobile}
@anastasia-bazaeva Так там смысл не в этом - теренарный оператор тут нужен как раз для того, чтобы не отображалась страница карточки чатов, потому что в мобильном разрешении - там только список чатов

2023-08-16 13:42 UTC, KirillKamratov commented on src/widgets/chats/components/Chat/index.tsx
> +        {window.location.pathname.includes('/in-work') ? (
@vierim Спасибо за комментарий, исправлю

2023-08-29 23:13 UTC, KirillKamratov commented
Была доделана большая часть работы:
- Доделана верстка (полностью)
- Данные чатов и конфликтов вынесены в стор (временное решение, пока нет бэка)
- Сделан большой рефакторинг

Из проблем, с которыми столкнулся:
Из-за стора (насколько я понял) в консоль сыпется ошибка:

<img width="1101" alt="Снимок экрана 2023-08-30 в 02 08 17" src="https://github.com/vierim/YaPomogayu-frontend/assets/102192184/fcb0d01e-6ab9-478f-9de7-e6bddb59c71f">

Насколько я понял, это происходит, из-за того что в action записывается значение типа Date, а это non-serializable value. Чтобы исправить - нужно внести в сам стор (файл index.ts в папке store) внести изменения, но я не очень понял, как это нужно сделать.

Касательно комментария, где описано, что волонтер достиг какого-то уровня (к примеру) - этот момент вроде как договорились оставить на бэк, об этом говорил @vierim.

Из долгов, которые остались на данный момент - сторибук, но его делать быстро очень.

Прошу посмотреть повторно, указать на недочеты.

2023-09-01 18:11 UTC, anastasia-bazaeva requested changes
Проделана большая работа! 
- Отлично, что есть отображение идентификатора чата в урле выбранного чата.
- Отлично, что есть верстка чата на странице админа на мобильном разрешении.

Остались некоторые моменты, которые нужно поправить:
- Промежуточные экраны между полной и мобильной версией на странице чатов ломаются. Мы можем перейти к отображению внутри попапа на более раннем брейкпоинте, чем сейчас.
![chats02](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/1c18a57e-9693-4c2c-84f2-d49d66a90a03)

- У нас сейчас идет туман по футеру, и он мешает видеть заготовки ответов администратору. На макете его нет, и я бы либо убрала, либо увеличила бы высоту блока или страницы, чтобы заготовки были выше зоны размытия.
![chats01](https://github.com/vierim/YaPomogayu-frontend/assets/102751317/5ed823e5-2ec4-4982-b262-6a2bb78af34e)
- Мы уже реализуем чаты внутри попапа. Такая же функциональность используется в профилях Волонтера и Реципиента. @vierim подскажи, пожалуйста, а мы в рамках этой задачи только для админов договорились делать чаты, или уже можно делать попапы с чатами на страницах заявок и в шапке ЛК остальным ролям?
- По поводу даты в сторе, есть [статья ](https://www.bam.tech/en/article/the-redux-best-practice-do-not-put-non-serializable-values-in-state-or-actions-explained)про бест практис на эту тему, может быть она чем-то поможет.

2023-09-02 09:46 UTC, vierim commented
Всплывающие окна с чатами у Волонтеров и Реципиентов -  я бы проверил, что вся верстка работает корректно и ждал бы бек.

2023-10-19 20:12 UTC, VladislavSerKir commented
Просмотрел весь код, сделал merge commit с development, исправил ошибки линтера и сторибука, ошибку двоения бокового меню в PageLayout  
![2023-10-19_20-18-05](https://github.com/ya-pomogau/frontend-fork/assets/83783362/95251067-69a0-4697-a2e3-c4fa18ee6257)
По сторибуку: большая часть переиспользуемых компонентов есть. Я бы добавил еще ChatList и в самом компоненте отображал бы инстансы чатов в отдельном компоненте например ChatItem, сейчас там как верстка и по нему тоже сделал бы сторибук компонент.
![2023-10-19_22-58-40](https://github.com/ya-pomogau/frontend-fork/assets/83783362/4ce587a4-81d3-476a-9f9e-f8f26c96f19f)

![2023-10-19_22-59-16](https://github.com/ya-pomogau/frontend-fork/assets/83783362/9bf08621-d063-4fb7-9b74-aa29c0a0d9ca)
По указанным выше комментариям:
- есть недочеты с отображением попапов чата при разных разрешениях 
- накладывающийся туман в чате
- модель пользователей и их чатов не соответствует текущей, что ожидаемо. В любом случае подстраивать
![2023-10-19_23-02-47](https://github.com/ya-pomogau/frontend-fork/assets/83783362/2ae80e7b-a9d7-447b-ab04-722c34ee8199)

![2023-10-19_23-06-48](https://github.com/ya-pomogau/frontend-fork/assets/83783362/7be86f46-c081-48a4-9645-8c68266dbc86)

На перспективу сделал бы влив ветки для продолжения разработки, на данный момент чаты доступны только по роутам

2023-11-24 19:40 UTC, kspshnik commented
Branch moved to base repo

2023-11-24 19:40 UTC, closed without merging